### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by fritzlb** [martin2250/ADCTouch#12]
This libraryworks flawlessly and ways better than every other soloution I tried :)
However a missing license technically permits nobody to use, modify and distribute this masterpiece which is sad :(

If you don't want to restrict any use of this software and therefore added no license you could add something like Unlicense to make your intentions clear :)

**Comment by martin2250** [comment]
Glad you like it! ADCTouch is now licensed under the MIT license, feel free to do with it as you like. Thanks for pointing it out :)

**Comment by fritzlb** [comment]
Thank you very much! :)
