### ISSUE TITLE
Error message:  if (digitalPin == NOT_A_PIN) return;

### ISSUE THREAD

**Issue by OliElNaesh** [martin2250/ADCTouch#4]
Hi I am trying to use your ADCTouch library and it works on my arduino, but i can't seem to upload it to my ATtiny85 microchip. I get the following error message:

C:\Program Files (x86)\Arduino\Arduino Projekt\libraries\ADCTouch-master\src\ADCTouch.cpp:13:31: error: return-statement with no value, in function returning 'int' [-fpermissive]

  if (digitalPin == NOT_A_PIN) return;

                               ^

exit status 1
Error compiling for board ATtiny85 @ 8 MHz  (internal oscillator; BOD disabled).

**Comment by martin2250** [comment]
Hi, 

thanks for your feedback. I updated the library on github. does the new version work?

**Comment by OliElNaesh** [comment]
IT WORKS!! Man if your forehead was in front of me right now I would kiss it!  Thank you!

was the only difference a -1?

**Comment by martin2250** [comment]
Haha, ok great!
yeah, it really was that simple. I suppose they changed something about the compiler warnings, maybe this is different for different OSes.
